version: '3'

services: 
  frontend:
    image: node:14
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
    ports:
      - 3000:3000
      - 45253:45253

backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - default
    depends_on:
      - db
    
  db:
    image: postgres:10.14
    container_name: rwbk_db
    environment: 
      - POSTGRES_DB=muistinnollaus
      - POSTGRES_PASSWORD=lorem
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - default