version: '3'

services:
  backend:
    build: 
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:10.14
    container_name: db
    environment: 
      - POSTGRES_DB=muistinnollaus
      - POSTGRES_PASSWORD=lorem
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - default
networks:
  default: